### ISSUE TITLE
CSV to JSON does not recognize line breaks in Windows 7

### ISSUE THREAD

**Issue by c3piio** [fitnr/SublimeDataConverter#1]
I have a very simple CSV that Access 2010 created. When I convert it to JSON the resulting text does not have any line breaks. I tried changing line_sep to:

"line_sep": false
"line_sep": "false"
"line_sep": "\r"

None of these recognize the line breaks in the CSV. A snapshot of the CSV and the first three rows are below:

"geonameid","name","asciiname","alternatenames","loc","feature_class","feature_code","country_code","cc2","admin1_code","admin2_code","admin3_code","admin4_code"
3,"Zamīn Sūkhteh","Zamin Sukhteh","Zamin Sukhteh,Zamīn Sūkhteh","[48.91667,32.48333]","P","PPL","IR",,"15",,,
5,"Yekāhī","Yekahi","Yekahi,Yekāhī","[48.9,32.5]","P","PPL","IR",,"15",,,

**Comment by fh-rsteier** [comment]
FWIW,, I had a similar issue today, where when trying to do any conversion, it simply returned an "empty" result (eg. converting to JSON returned `[]`, even using the sample data that is on the README).

The solution I found in Sublime text was to go to View > Line Endings > Unix, then the conversion worked.

I'm running Sublime Text 3, with Windows 10, too.

**Comment by rsteier** [comment]
FWIW, I had a similar issue today, where when trying to do any conversion, it simply returned an "empty" result (eg. converting to JSON returned [], even using the sample data that is on the README).

The solution I found in Sublime text was to go to View > Line Endings > Unix, then the conversion worked.

I'm running Sublime Text 3, with Windows 10, too.
