### ISSUE TITLE
A package for Sublime Text 2... (no mention of ST3 in title)

### ISSUE THREAD

**Issue by geckoseo** [fitnr/SublimeDataConverter#19]
> A package for Sublime Text 2 for converting CSV data to other formats.

Is the missing reference to ST3 just an oversight? 

Can you confirm that the package is alive and that you are still interested in keeping it maintained?

It appears to be a tremendously useful tool, but I nearly didn't install it because of the title.

Only after I saw the ST3 badge did I think to give it a go, and it seems to work just fine in ST3 for the very brief tests I've done so far.

So firstly a quick word of thanks to you for making it available, and I hope also some words of encouragement for you to keep it going. 

It really is appreciated.

**Comment by fitnr** [comment]
Title blurb corrected to "Sublime Text"
