### ISSUE TITLE
breaks in Sublime build 3132

### ISSUE THREAD

**Issue by old9** [fitnr/SublimeDataConverter#23]
using the sample data in README:

```
name,value,fruit,date
Alice,10,Apple,"Sep. 12, 2016"
Bob,11,Blueberry,"Sep. 13, 2016"
Chris,12,Orange,"Sep. 14, 2016"
```
convert to Ruby gives this:
![image](https://cloud.githubusercontent.com/assets/536624/26500522/d011b2f0-4268-11e7-89c7-9a3951a4cff8.png)

convert to HTML table gives this:
![image](https://cloud.githubusercontent.com/assets/536624/26500560/f0e63d20-4268-11e7-9f19-72abf7b69e2a.png)

and so on...

Sublime Text build 3132 @ Windows 10

**Comment by fitnr** [comment]
Try changing the `"line_sep"` settings to `"\n"`. See the [settings file](https://github.com/fitnr/SublimeDataConverter/blob/master/DataConverter.sublime-settings#L8):
```
  // Newline character for output. Set to either a character or null.
  // When null, DataConverter uses the OS line separator, which is "\r" in Windows.
  "line_sep": null,
```

**Comment by old9** [comment]
This works, thanks!

**Comment by fitnr** [comment]
I checked the SublimeText API docs, and it's been updated since I made this plugin years ago. There's now a way to check the line endings settings of the current document, so in the next release I'm removing the `line_sep` option in favor of using the current document's line endings.
