### ISSUE TITLE
Not working for build 3126

### ISSUE THREAD

**Issue by frisky-dingo** [fitnr/SublimeDataConverter#24]
In ST3 build 3126 (Win10), I can't seem to get it to convert data to anything.  Using the example data from the README file (CSV data with the fields name, value, fruit, and date), I get exactly the same results shown in the post by old9 (https://github.com/fitnr/SublimeDataConverter/issues/23).  The only difference is that the issue old9 reported was for one of the dev builds (3132).

Just thought I should pass this along.

**Comment by fitnr** [comment]
Tested, works fine.
