### ISSUE TITLE
Does not seem to work on Sublime 3.1.1

### ISSUE THREAD

**Issue by misilot** [fitnr/SublimeDataConverter#25]
When I try turning the example:

name,value,fruit,date
Alice,10,Apple,"Sep. 12, 2016"
Bob,11,Blueberry,"Sep. 13, 2016"
Chris,12,Orange,"Sep. 14, 2016"

into ruby I get 

```
[

	{}

];```

or a TSV

```
name,value,fruit,date

```

Thanks!

**Comment by misilot** [comment]
I was able to get it to work after changing the line endings to Unix.

**Comment by fitnr** [comment]
There's an ample description of each setting in [DataConverter.sublime-settings](https://github.com/fitnr/SublimeDataConverter/blob/master/DataConverter.sublime-settings).
