### ISSUE TITLE
Unable to convert csv to json

### ISSUE THREAD

**Issue by Nicob75** [fitnr/SublimeDataConverter#30]
Hello, whenever I try to convert a csv to a json, for example :

```
id,name,size
1,julia,10
2,thomas,20
3,alex,30
```

I get the following error :
```
DataConverter: CSV Sniffer found headers
DataConverter: Unable to set syntax (resource "Packages/JavaScript/JSON.tmLanguage" not found).
```

And my csv is transformed into an empty json array: []

I am using Sublime Text Build 4143 from the stable channel on Windows 11.

Any idea of the issue ?

**Comment by fitnr** [comment]
I can't reproduce, but it looks like the Sublime API has been updated and the suggested way to set the syntax has changed. I will work on a fix.

**Comment by fitnr** [comment]
Just pushed an update with a fix.

**Comment by Nicob75** [comment]
Hi @fitnr, awesome thank you for the fix ! I just upgraded to your new version and indeed I don't have the error message anymore. However, my csv is still transformed to an empty array "[]" :( Does it transform into the correct json on your end ?

**Comment by fitnr** [comment]
If you're on Windows, play around with the line endings settings, that may be the issue.
